pipeline{
    agent any
    stages{
        stage("uptime"){
            steps{
                sh '''
                uptime
                '''
            }
            
        }
        stage("disk-filesystem"){
            steps{
                sh '''
                df -kh
                '''
            }
        }
        stage("Ram-used"){
            steps{
                sh '''
                free -h
                '''
            }
            
        }
    }
}